name: Build and run ROS2 tests

on:
  pull_request:
    branches: [ dev, main, 'stabilization/**' ]
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:

    runs-on: self-hosted

    continue-on-error: true

    container:
      image: ros:humble-ros-base

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_TOKEN }} 
        path: wisevision_notifcation_manager_ws/src/wisevision_notifcation_manager

    - name: Configure Git for HTTPS authentication
      run: |
        git config --global url."https://${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Import repositories using vcs
      run: |
        cd wisevision_notifcation_manager_ws/src
        vcs import --recursive < wisevision_notifcation_manager/wisevision_notification_manager.repos

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y curl
        apt-get install -y libyaml-cpp-dev
        apt-get install -y libjsoncpp-dev
        apt-get install -y libcurl4-openssl-dev
        rosdep update --include-eol-distros
        rosdep install --from-path . -i -y --rosdistro humble

    - name: Build test
      run: |
        cd wisevision_notifcation_manager_ws/src
        . /opt/ros/humble/setup.sh
        colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-up-to wisevision_notification_manager
    
    - name: Clean up workspace
      if: always()
      run: |
        sudo rm -rf wisevision_notifcation_manager_ws

